title: "My Cybersecurity Portfolio"
description: "Pentester | Security Researcher | Cybersecurity Enthusiast"
author: "Your Name"
email: youremail@example.com
baseurl: "" # leave empty for user.github.io
url: "https://yourusername.github.io"

# Prevent GitHub Pages from trying to apply a theme
theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag
