title: "./ 3xp-loit:~#"
description: "Hack Enumerate Harder!. Eat. Sleep. Repeat."
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# This keeps your writeup folders working
collections:
  htb:
    output: true
  thm:
    output: true
  hsm:
    output: true
